spring:
  profiles:
    active: local
  main:
    allow-circular-references: true
jwt:
  expiration: 86400000 # 24 hours in milliseconds

# RSA configuration is handled in profile-specific files
rsa:
  public-key: classpath:certs/public-key.pem
  private-key: classpath:certs/private-key.pem

app:
  oauth2:
    authorized-redirect-url: http://localhost:3333/oauth2/redirect
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}  
      redirect-uri: http://localhost:8888/oauth2/callback/google


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

